.circleci/config.yml
test/staking.ts

1. Up the iteration count for the distribution tests when running in circle ci. This should lower the chance that the tests will fail.
2. I also was unable to get the tests failing locally, even after running multiple times. This may be due to running node 16 locally, vs running node 14 in the circle ci image, so updated that as well.

NET-100 Fix distribution tests

---

contracts/Channels.sol
contracts/Staking/Directory.sol
test/channels.ts
test/listings.ts
test/payments/ticketing.ts
test/staking.ts
test/utils.ts

Summary of changes:
- Create `Channel` contract to store user's current channel on-chain.
- Update `scan(uint128 point)` to `_scan(uint256 point, uint256 epochId)`
- Create `scan(bytes memory pk, uint256 epochId, uint8 channel)` as an entry method to hash inputs and scan.
- Create `derivePoint` method to hash `public key, current epoch id, and channel` using `keccak256`.

NET-104 Create channel contract and update scan function

---

test/staking.ts

Fixed flaky tests:
- `should distribute scan results amongst stakees proportionally - all equal`
- `should distribute scan results amongst stakees proportionally - varied stake amounts`
Previous random generation method had a failure rate of 6.44%. New method does not fail.
Test Logs: [output.zip](https://github.com/dn3010/sylo-ethereum-contracts/files/8413828/output.zip)

NET-111-fixing-flaky-tests

---

contracts/Listings.sol
test/listings.ts

Instead of nodes posting a multiaddr to connect to with a libp2p client, nodes will instead post a public http endpoint. This endpoint can then be queried for additional information (such as the node's multiaddr).
Rename `multiaddr` to`publicEndpoint` in listings struct.

NET-141 Public Endpoint

---

contracts/Payments/Ticketing/RewardsManager.sol
test/payments/ticketing.ts

The previous changes to the reward calculation introduced a bug that mistakenly omitted the initial claim value from the final calculation. This PR resolves that issue and adds another test case to ensure that particular edge case does not get missed.

NET-328 Fix Reward Claim

---

docker/rootnet-with-protocol/Dockerfile

Currently, there are 2 issues with the sylo node testnets:
- The seed docker version for root network is outdated.
- The sleep function in docker-compose file does not guarantee other services can wait until the blockchain node is ready.
This PR is to fix the first issue.

NET-397 Update seed docker version

---

contracts/Registries.sol
docs/spec.md
test/payments/ticketing.ts
test/registries.ts
test/utils.ts

The minDelegatedStake field is intended to be configured by nodes to set a minimum Sylo amount that a delegate must provide when staking. It was decided that we did not need to use this value for phase 2, as its main purpose is to prevent the list of delegated stakers being too long, which could have an implication on gas costs, but this no longer applies.
However the field still exists in the Registry, and is still passed in when calling register. We should remove this field from the contract for phase 2 as it creates unnecessary confusion.
- Removed the minDelegatedStake field from the Registry struct within the Registries contract
- Removed the minDelegatedStake parameter within the register function call
- Amended the test cases by removing the now extra parameter

NET-352 remove minDelegatedStake from registries contract

---

contracts/Payments/Ticketing.sol
docs/overview.md
test/payments/ticketing.ts

The primary restriction regarding Node operators and Seekers is that a Node runner must have registered a valid Seeker with their Node when their Node joins an epoch. There is no restriction that the Node runner must retain ownership of their Seeker after their Node joins an epoch in order for their Node to continue to redeem tickets during that epoch. For example it is valid to sell your Seeker immediately after your Node joins an epoch (there is another check in EpochsManager that would prevent the same seeker being reused).
However there is an additional `require` call in the `redeem` method that checks if the Node's account has a valid Seeker account registered with it. This is unnecessary as the `joinNextEpoch` method already has the validation to ensure the Node's registered Seeker …

NET-445 (SLP-01) Fix `revokeSeekerAccount` preventing ticket redemption

---

contracts/Payments/Ticketing.sol
test/payments/ticketing.ts

The audit noted that it was possible for a ticket to be redeemed with a generation block greater than the current epoch's end block.
This PR prevents that by additionally checking if the ticket generation block is less than or equal to than the current block.
- Add additional check for ticket generation block
- Remove require check that the ticket generation block is within the current epoch in the `redeem` function. This is because we also perform the same check in `calculateWinningProbability`, so it is unnecessary to do here as well.

Net 447 (SLP-03) Adjust ticket block check

---

contracts/Payments/Ticketing.sol
contracts/Payments/Ticketing/RewardsManager.sol
contracts/Staking/Directory.sol
contracts/Staking/Manager.sol
contracts/Utils.sol

We perform integer down casts throughout the contract code base. These casts are unsafe as if the value is larger than the maximum value we are casting, then the behaviour of the contract will be unpredictable.
We can use the `SafeCast` which will explicitly throw an error if the value exceeds the maximum. This will prevent unexpected behaviour from happening.
- Replace any integer casts with the `toX` form from the SafeCast lib

NET-449 (SLP-05) Use SafeCast lib to avoid integer overflow

---

contracts/Registries.sol
deploy/00_deploy_phase_two.ts
deploy/genesis.config.ts
test/registries.ts
test/utils.ts

Currently we validate that seeker signatures are submitted within a `proofDuration` time frame. This is to prevent the signature from being reused at a later date. This approach is a remnant of when we were relying on an external Oracle to validate the Seeker proof. This is no longer necessary and we can now just store and use a nonce with each signature to ensure that each one is unique.
- Replace `proofDuration` with a `nonce` in the signature message
- Track nonces in storage to prevent reuse

NET-450 (SLP-06) Improve seeker account signatures

---

contracts/Payments/Ticketing.sol
test/payments/ticketing.ts

We hash random integers for use as the sender and redeemer commits. The audit identified this as not being secure enough, and suggested we should double hash and use a salt to improve the hash security.
- Modify the commit creation to use the ticket generation block as a salt, and perform `keccak256` twice.

NET-451 (SLP-07) Improve hashing of sender and redeemer rands

---

contracts/Payments/Ticketing.sol
contracts/Payments/Ticketing/RewardsManager.sol
contracts/Staking/Manager.sol

The ERC20 `transfer` and `transferFrom` return `true` when those calls are successful. The contracts should verify those results to prevent unexpected behaviour.
- Use `SafeERC20` for all `transfer` and `transferFrom` calls to verify their execution

NET 454 (SLP-11) Verify transfer call

---

contracts/ECDSA.sol
contracts/Epochs/Manager.sol
contracts/Manageable.sol
contracts/Payments/Ticketing.sol
contracts/Payments/Ticketing/Parameters.sol
contracts/Payments/Ticketing/RewardsManager.sol
contracts/Registries.sol
contracts/Staking/Directory.sol
contracts/Staking/Manager.sol

We use the `Ownable` lib to allow the Sylo to administrate the network protocol. This is an industry standard but imposes some risk in the case we accidentally transfer to an account that is invalid or does not exist. This PR replaces the Ownable contract with `Ownable2Step`, which forces the transferee of the ownership to explicitly send a claim for the ownership in order for the ownership to transer.
The `Ownable2Step` interface https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/access/Ownable2StepUpgradeable.sol
- Replace `Ownable` with `Ownable2Step`

Net 456 (SLP-13) Safe ownership transfer

---

contracts/ECDSA.sol
contracts/Epochs/Manager.sol
contracts/Manageable.sol
contracts/Payments/Ticketing.sol
contracts/Payments/Ticketing/Parameters.sol
contracts/Payments/Ticketing/RewardsManager.sol
contracts/Registries.sol
contracts/Staking/Directory.sol
contracts/Staking/Manager.sol
contracts/TestSeekers.sol
contracts/Token.sol
contracts/Utils.sol
hardhat.config.ts
package-lock.json

Solc frequently launches new versions of the compiler. Using an outdated version of the compiler can be problematic, especially if there are errors that have been made public or known vulnerabilities that affect this version.
Solidity branch 0.8.17 has important bug fixes, so it is recommended to use the most up to date version of the pragma.

NET-457 (SLP-14) Update solc version to 0.8.18

---

contracts/Epochs/Manager.sol
contracts/Payments/Ticketing.sol
contracts/Staking/Directory.sol

Event indexing of smart contracts can be used to filter during the querying of events. This can be very useful when making dApps or in the off-chain processing of the events in our contract, as it allows filtering by specific addresses, making it much easier for developers to query the results of the invocations.
It could be convenient to review the Sylo Project to ensure that all the events have the necessary indexes for the correct functioning of the possible dApps. Addresses are usually the best argument to filter an event.

NET-459 (SLP-16) Add event index

---

.solcover.js
contracts/Registries.sol
contracts/epochs/EpochsManager.sol
contracts/interfaces/IRegistries.sol
contracts/interfaces/epochs/IEpochsManager.sol
contracts/interfaces/payments/ISyloTicketing.sol
contracts/interfaces/payments/ticketing/IRewardsManager.sol
contracts/interfaces/payments/ticketing/ITicketingParameters.sol
contracts/interfaces/staking/IDirectory.sol
contracts/interfaces/staking/IStakingManager.sol
contracts/libraries/Manageable.sol
contracts/libraries/SyloUtils.sol
contracts/mocks/TestSyloUtils.sol
contracts/payments/SyloTicketing.sol
contracts/payments/ticketing/RewardsManager.sol
contracts/payments/ticketing/TicketingParameters.sol
contracts/staking/Directory.sol
contracts/staking/StakingManager.sol
test/epochs.test.ts
test/payments/ticketing.test.ts
test/registries.test.ts
test/staking.test.ts

Inputs to functions should be validated to prevent any unexpected behaviour. 
Some examples:
- Methods that take in addresses for contracts should be validated that they not address(0). Can also use `supportsInterface`.
- Range validation for certain values (proofDuration for Registries contract)
- Compute ticket hash may be unnecessary as the hash is never validated

NET-463 (SLP-20) Validate input

---

contracts/Registries.sol
test/registries.test.ts

A valid seeker registration should compose of both a non zero seeker id and a non zero seeker account field in the registry. We currently overwrite the seeker id field to zero for the existing registration when using the same seeker id. We should do the same for the seeker field as well.

NET-477 Delete duplicated seeker account after another node sets seeker account

---

contracts/payments/SyloTicketing.sol

The second audit review noted that the movement of `usedTickets[ticketHash] = true` presented a vulnerability as it ended up being placed after an external call.
This PR reverts that change.

NET-484 Fix used tickets reentrancy problem

---

contracts/interfaces/payments/ISyloTicketing.sol
contracts/payments/SyloTicketing.sol
test/payments/ticketing.test.ts

In phase 3, the node will check the senders' deposits when they request relays to the node. Instead of making a call to the blockchain for each relay request that is highly expensive in terms of API call rate, the nodes will store senders' deposits in their own caches, and just need to query on chain after an unlock duration to update data.
However, we have to make sure that the information of senders' deposit in cache must be up-to-date, so that the node can eliminate from being exploited by some bad senders. 
There are an issue that might negatively affect the node
**Problem ** 
The senders' deposits might be burned by other nodes after this node saves the valid senders' deposits in its cache. Because this node depends on its cache, (just query again after the unlock_duration time), …

NET-444 Optimise event ticket validation in notify events

---

.circleci/config.yml
contracts/AuthorizedAccount.sol
contracts/interfaces/IAuthorizedAccount.sol
contracts/interfaces/payments/ISyloTicketing.sol
contracts/payments/SyloTicketing.sol
package.json
test/authorizedAccount.test.ts
test/payments/ticketing.test.ts
test/utils.ts

As outlined in this here https://www.notion.so/futureverse/RFC-Alleviating-user-friction-in-ticket-creation-process-1b1416776aee4532b513c638ae976e23#1616abd90910416da6fc434fe41e5e0a, we can modify the signature verification check for tickets to rely on a signature from a different wallet, one that has been delegated by the holder of the deposit.
This solution involves:
- Implement new contract to store authorised accounts
- Add additional field in current ticket structure to indicate if the signature is from the main account or a delegated account
- Check permission of the delegated account before withdrawing sender deposit
- Verify signature if delegated account is used in the ticket
- implement authorized account contract
- integrate authorized account contract with ticketing contract
- …

NET-550 Add-delegated-account

---

contracts/AuthorizedAccounts.sol
test/authorizedAccount.test.ts

So far, if the `_removePermissions` is called, we always update the permission's `unauthorizedAt` field even when it is already unauthorized. User would accidentally create a valid period between the first `unauthorizedAt` and the new `unauthorizedAt`. This PR is to fix the issue and only update `unauthorizedAt` if the permission is authorized.

NET-617 Only update unauthorizedAt if the permission is authorized

---

scripts/nodes.json

Minor PR to support https://github.com/futureversecom/sylo-protocol-sdk/pull/60. Includes an adjustment to the registry public endpoints in the ganache testnet to use different ports. This will better support running and connecting to the nodes locally.

SM-106 Update testnet

---

.github/workflows/deployment.yml
common/contracts.ts
contracts/SeekerPowerOracle.sol
contracts/interfaces/IFuturePassRegistrar.sol
contracts/interfaces/ISeekerPowerOracle.sol
contracts/mocks/TestFuturepassRegistrar.sol
test/seekerOracle.test.ts
test/utils.ts

This PR adds the interface for the Seeker Oracle contract, as well as a basic implementation. The Seeker Oracle works by keeping a record of a "oracle" account, and also a mapping of Seeker Ids to Seeker Power levels. The oracle account to set the a Seeker's power level mapping by calling the method `setSeekerPowerRestricted`. Only the oracle account and the owner account (deployer) are allowed to call this method.
There is also an additional way to set the seeker's power level by calling the unrestricted method `registerSeekerPower`. The register method takes an additional parameter, a `proof` message. The proof is a specific message that has been signed by the `oracle` account. The structure of the message is as follows:
`${seekerId}:${seekerPower}`
The register function only allows …

SM-117 Seeker Oracle
